export { loginSchema, registerSchema } from "./schemas/auth-schema"
export type { LoginInput, RegisterInput } from "./schemas/auth-schema"
export type { AuthUser, AuthResponse } from "./types/auth-type"
export { authRouter } from "./server/route"
export { useLogin, useRegister, useLogout } from "./api/use-auth"
